import os

DB_NAME = os.getenv("DB_NAME", "academia.db")
DB_PATH = os.path.join(os.path.dirname(os.path.dirname(__file__)), "database", DB_NAME)

ROLE_ADMIN = "ADMIN"
ROLE_SECRETARIA = "SECRETARIA"

STATUS_ACTIVO = "ACTIVO"
STATUS_RETIRADO = "RETIRADO"
STATUS_REINGRESANTE = "REINGRESANTE"

CUOTA_PENDIENTE = "PENDIENTE"
CUOTA_PARCIAL = "PARCIAL"
CUOTA_PAGADO = "PAGADO"
CUOTA_VENCIDO = "VENCIDO"

METODO_EFECTIVO = "EFECTIVO"
METODO_YAPE = "YAPE"
METODO_PLIN = "PLIN"
METODO_TRANSFERENCIA = "TRANSFERENCIA"

TIPO_BECA_PORCENTAJE = "PORCENTAJE"
TIPO_BECA_MONTO_FIJO = "MONTO_FIJO"

TIPO_MOVIMIENTO_ENTRADA = "ENTRADA"
TIPO_MOVIMIENTO_SALIDA = "SALIDA"
TIPO_MOVIMIENTO_AJUSTE = "AJUSTE"

TIPO_USO_CONSUMO_INTERNO = "CONSUMO_INTERNO"
TIPO_USO_VENTA = "VENTA"

CATEGORIA_INICIAL = [
    ("3-5", 3, 5),
    ("6-8", 6, 8),
    ("9-12", 9, 12),
    ("13-15", 13, 15),
    ("16-18", 16, 18),
]

CATEGORIA_PRODUCTO_INICIAL = [
    "INSUMO_DEPORTIVO",
    "INSUMO_ALIMENTO",
]

DEFAULT_ADMIN_USER = "admin"
DEFAULT_ADMIN_PASS = "admin123"

BACKUP_DIR = os.path.join(os.path.dirname(os.path.dirname(__file__)), "backups")
