from models.persona import Persona
from models.usuario import Usuario
from models.apoderado import Apoderado
from models.estudiante import Estudiante
from models.estudiante_apoderado import EstudianteApoderado
from models.categoria import Categoria
from models.tarifa import Tarifa
from models.beca import Beca
from models.matricula import Matricula
from models.matricula_beca import MatriculaBeca
from models.cuota import Cuota
from models.pago import Pago
from models.detalle_pago import DetallePago
from models.categoria_producto import CategoriaProducto
from models.producto import Producto
from models.movimiento_inventario import MovimientoInventario
from models.configuracion import Configuracion
from models.log import Log
